build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.17
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aaa
  commands: make aaa
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: liutestlt
  repo: test-repo1
